package router

// stopWords contains common English stop words excluded from TF-IDF analysis.
var stopWords = map[string]bool{
	"a": true, "about": true, "above": true, "after": true, "again": true,
	"against": true, "all": true, "am": true, "an": true, "and": true,
	"any": true, "are": true, "as": true, "at": true, "be": true,
	"because": true, "been": true, "before": true, "being": true, "below": true,
	"between": true, "both": true, "but": true, "by": true, "can": true,
	"could": true, "did": true, "do": true, "does": true, "doing": true,
	"down": true, "during": true, "each": true, "few": true, "for": true,
	"from": true, "further": true, "get": true, "got": true, "had": true,
	"has": true, "have": true, "having": true, "he": true, "her": true,
	"here": true, "hers": true, "herself": true, "him": true, "himself": true,
	"his": true, "how": true, "i": true, "if": true, "in": true,
	"into": true, "is": true, "it": true, "its": true, "itself": true,
	"just": true, "let": true, "may": true, "me": true, "might": true,
	"more": true, "most": true, "must": true, "my": true, "myself": true,
	"no": true, "nor": true, "not": true, "now": true, "of": true,
	"off": true, "on": true, "once": true, "only": true, "or": true,
	"other": true, "our": true, "ours": true, "ourselves": true, "out": true,
	"over": true, "own": true, "quite": true, "rather": true, "re": true,
	"s": true, "same": true, "shall": true, "she": true, "should": true,
	"so": true, "some": true, "such": true, "t": true, "than": true,
	"that": true, "the": true, "their": true, "theirs": true, "them": true,
	"themselves": true, "then": true, "there": true, "these": true, "they": true,
	"this": true, "those": true, "through": true, "to": true, "too": true,
	"under": true, "until": true, "up": true, "upon": true, "us": true,
	"very": true, "was": true, "we": true, "were": true, "what": true,
	"when": true, "where": true, "which": true, "while": true, "who": true,
	"whom": true, "why": true, "will": true, "with": true, "won": true,
	"would": true, "you": true, "your": true, "yours": true, "yourself": true,
	"yourselves": true, "also": true, "going": true, "like": true,
	"made": true, "much": true, "need": true, "new": true,
	"one": true, "really": true, "right": true, "said": true, "say": true,
	"see": true, "since": true, "still": true, "take": true, "tell": true,
	"thing": true, "think": true, "though": true, "try": true, "use": true,
	"used": true, "using": true, "want": true, "way": true, "well": true,
	"went": true, "work": true,
	"yes": true, "yet": true, "able": true, "back": true, "even": true,
	"give": true, "go": true, "good": true, "great": true, "help": true,
	"keep": true, "know": true, "long": true, "look": true, "many": true,
	"old": true, "put": true, "run": true, "set": true, "show": true,
	"two": true, "come": true, "every": true, "first": true, "already": true,
}
